### ISSUE TITLE
seq_info.csv should be consistent among all subdirectories

### ISSUE THREAD

**Issue by nhoffman** [nhoffman/ya16sdb#12]
```
==> 20180324/dedup/1200bp/named/seq_info.csv <==
seqname,version,accession,name,description,tax_id,modified_date,download_date,version_num,source,keywords,organism,length,ambig_count,strain,mol_type,isolate,isolation_source,seq_start,seq_stop,is_type
==> 20180324/dedup/1200bp/named/filtered/seq_info.csv <==
seqname,tax_id
```

The second file should have the same contents as the first. Find a different name for the latter. tax_ids.csv?

**Comment by crosenth** [comment]
Also change feather output filename: details_out.feather --> filter_details.feather

**Comment by crosenth** [comment]
[Fixed](https://github.com/nhoffman/ya16sdb/commit/2a989f8380b84a669e9bb38b9123a0a4ccddfe67) the missing seq_info.csv columns in named/filtered

[filter_details.feather](https://github.com/nhoffman/ya16sdb/commit/2a989f8380b84a669e9bb38b9123a0a4ccddfe67)
