### ISSUE TITLE
consider post-filtered 'type' sequences for target of vsearch

### ISSUE THREAD

**Issue by dhoogest** [nhoffman/ya16sdb#14]
Discussion item:

For the pipeline phase where closest type strain is assessed via vsearch, it would perhaps be higher value for the type strains to be considered post-filtering (in other words, the similarity to closest trusted type strain is determined). I don't know how many of the 'from type' records end up dropped by either do-not-trust or deenurp filter_outliers, but it is a non-zero list.

**Comment by dhoogest** [comment]
@crosenth @nhoffman what do you think?

**Comment by crosenth** [comment]
Are you proposing an improvement to the "type strain hit" column in the species bokeh plots?

**Comment by dhoogest** [comment]
yes, and we're using that info in the blast details for NGS16S reports as well.

**Comment by crosenth** [comment]
Got it, so a filtered/trusted/types output dir

**Comment by dhoogest** [comment]
@crosenth y
es I think it does

**Comment by crosenth** [comment]
Alright it will go out with the v0.4 release
