### ISSUE TITLE
view outliers app

### ISSUE THREAD

**Issue by nhoffman** [nhoffman/ya16sdb#16]
Tests

- [x] search for sequence name
- [x] search for accession
- [x] search for accession with multiple hits
- [x] url-encode accession

**Comment by crosenth** [comment]
Modifications

- [ ] Make box select the default menu bar tool
- [x] open up new tab when selecting records and match species in table
- [ ] add rank order to axes when using dist
- [ ] add match species to possible axes
- [ ] add new multi-drop down menus [selection visibility] [isolation_source match_species outlier_detection type published]
- [ ] improve showing of selected glyphs (move to front, decrease opacity of other glyphs, etc)

**Comment by crosenth** [comment]
In order to accomplish "pin requirements" I need to raise an Issue with https://github.com/plotly/dash-core-components to get more information as to why axes autorange values are no longer available in figure.layout.[xaxis yaxis].range after dash-core-components version 0.30.1.

**Comment by crosenth** [comment]
https://github.com/plotly/dash-core-components/issues/321

**Comment by crosenth** [comment]
Beta [release](http://ya16sdb.labmed.uw.edu/)

**Comment by crosenth** [comment]
I have created Issues for the four remaining tasks/enhancements: https://github.com/nhoffman/ya16sdb/issues/18, https://github.com/nhoffman/ya16sdb/issues/19, https://github.com/nhoffman/ya16sdb/issues/20, https://github.com/nhoffman/ya16sdb/issues/21
