### ISSUE TITLE
Wrong source specified for trusted types blastdb

### ISSUE THREAD

**Issue by dhoogest** [nhoffman/ya16sdb#17]
https://github.com/nhoffman/ya16sdb/blob/716320fd2fa6fe68fb5d0397e0053ceeefed636b/SConstruct#L669

Should be `trusted_type_fa`

**Comment by dhoogest** [comment]
@crosenth mind fixing this and rolling with the next or release?

**Comment by crosenth** [comment]
https://github.com/nhoffman/ya16sdb/blob/master/SConstruct#L671
