### ISSUE TITLE
allow url-encoding of all selectors

### ISSUE THREAD

**Issue by nhoffman** [nhoffman/ya16sdb#23]
for example ``https://ya16sdb.labmed.uw.edu?color=outliers&shape=type_strains&x=dist_pct&y=rank_order``

**Comment by crosenth** [comment]
http://ya16sdb.labmed.uw.edu/?color=is_out&shape=is_type&x=dist_pct&y=rank_order&selection_isolation_source=sea+water&visibility_pubmed_id=Yes,No

url selector arguments are: 

1. x 
2. y
3. color
4. shape
5. selection_[is_out, is_type, match_species, pubmed_id, isolation_source]
6. visibility_[is_out, is_type, match_species, pubmed_id, isolation_source]

**Comment by crosenth** [comment]
https://github.com/nhoffman/ya16sdb/commit/d813b681b765e12945a9417dcfca6add80715134
