### ISSUE TITLE
roll back https://github.com/nhoffman/ya16sdb/pull/31

### ISSUE THREAD

**Issue by dhoogest** [nhoffman/ya16sdb#34]
Apparently the inclusion of species_group column in created some issues for other pipeline uses. We've come up with an alternate plan for building ref feather files in custom shapes, so it isn't necessary to include the NGS16S-consumed columns added in !31

**Comment by dhoogest** [comment]
@crosenth - Noah's suggestion. This can happen whenever convenient

**Comment by crosenth** [comment]
https://github.com/nhoffman/ya16sdb/commit/2baf370d8e81f86fd610e50e8a2fc29cc054f1d3
