### ISSUE TITLE
genome identifier

### ISSUE THREAD

**Issue by nhoffman** [nhoffman/ya16sdb#36]
We need to define an identifier that can be used to group records by genome sequencing project: for shotgun assemblies, accessions refer to a contig, and as a result multiple accessions can refer to the same assembly. 

see also #32

**Comment by marykstewart** [comment]
You may already have tried this, but just in case not:  
The whole genome project number (AGXQ01 or QSCG01 for the two test assemblies I was just using, see attachments) pulls up the assembly in the NCBI assembly database and the contigs in the nucleotide database (plus the whole genome project record, which doesn't have sequence directly associated with it). So it seems like that might serve as a bridge. The GCF accession (only refseqs have this) will also do this, but the GCA accession will not (both refseqs and non-refseqs have). Could be argued that assemblies that don't qualify for refseq status should be excludable anyway (QSCG01 is one of those, the reasons for exclusion from refseq are in the record summary and don't inspire confidence).  
  
![AGXQ01_report](https://user-images.githubusercontent.com/47676222/65548614-a0920a00-ded0-11e9-8e2e-082b4c83270c.png)
![QSCG01_report](https://user-images.githubusercontent.com/47676222/65548632-a687eb00-ded0-11e9-88b2-5439426cfa21.png)

**Comment by crosenth** [comment]
The release 0.7.3 seq_info.csv includes two columns wgs accessions "master" and "assembly_genbank"

**Comment by crosenth** [comment]
Anything left on this Issue?
