### ISSUE TITLE
regex bug for long genome accessions

### ISSUE THREAD

**Issue by dhoogest** [nhoffman/ya16sdb#37]
For example, `NZ_CAADIT010000001` from accession `CAADIT010000001` is transformed by the regular expression in https://github.com/nhoffman/ya16sdb/blob/f429540104b6c151acd65a968a51446aa33fcd63/bin/extract_genbank.py#L26 to `ADIT01000000`. Results in duplicate records for this genome

**Comment by crosenth** [comment]
https://ncbiinsights.ncbi.nlm.nih.gov/2019/03/22/new-accession-formats-refseq-release-93/

**Comment by crosenth** [comment]
For record keeping these are the current formats:

<img width="572" alt="Screen Shot 2019-08-08 at 10 12 37 AM" src="https://user-images.githubusercontent.com/1760683/62723287-30cdcb80-b9c5-11e9-86f3-f972d0993f42.png">
https://www.ncbi.nlm.nih.gov/Sequin/acc.html

<img width="673" alt="Screen Shot 2019-08-08 at 10 19 27 AM" src="https://user-images.githubusercontent.com/1760683/62723680-15af8b80-b9c6-11e9-9204-2e56ce00fecf.png">
https://www.ncbi.nlm.nih.gov/books/NBK21091/table/ch18.T.refseq_accession_numbers_and_mole/?report=objectonly

**Comment by crosenth** [comment]
https://github.com/nhoffman/ya16sdb/commit/e26350798482c8b8535e011d2242230430047e0a
