### ISSUE TITLE
Best match 16S type strain record in ya16sdb web interface does not match data in NGS16S output

### ISSUE THREAD

**Issue by marykstewart** [nhoffman/ya16sdb#44]
Hi Chris, linking here to the issue I made in the molmicro github a couple of weeks ago https://gitlab.labmed.uw.edu/molmicro/mkrefpkg/-/issues/83
  
Will this be part of the upcoming release?  
  
It just occurred to me...is this why you and Noah think there is a misclassified E. faecalis type strain, WRT example NZ_CABGZA010000007_337_1876 (coordinates have changed slightly)? It seems like this must just be the ya16sdb web interface bug. There are no Enterococcus type strains in the NCBI_16s_types_details when that 'Enterococcus faecalis' record is blasted...and that database is unfiltered, so if there was one lurking, it should show up. https://share.labmed.uw.edu/molmicro/sanger/report/2021/09/30/2053025_ad_hoc_20210930150544_NZ_CABGZA010000007_337_1876.html
   
<img width="898" alt="Screen Shot 2021-09-30 at 3 02 09 PM" src="https://user-images.githubusercontent.com/47676222/135536437-d8cb70f4-e321-4113-8989-45617028d799.png">

<img width="932" alt="Screen Shot 2021-09-30 at 3 09 46 PM" src="https://user-images.githubusercontent.com/47676222/135536678-40a95a21-b4b5-4ab6-b365-dba380b6b430.png">  
  
<img width="1681" alt="Screen Shot 2021-09-30 at 3 11 39 PM" src="https://user-images.githubusercontent.com/47676222/135537888-40afe77a-3844-461d-bccf-da407517bbae.png">

**Comment by crosenth** [comment]
Yes that is a bug in the web interface, the nearest type strain is just itself.  This bug has been lingering for a while but it should hopefully, finally be fixed with this release

**Comment by crosenth** [comment]
This should be fixed with the bump in Pandas version in the requirements.txt file https://github.com/nhoffman/ya16sdb/commit/dbf470d311583ce9c768da15b8be6dbdd1824edc
