### ISSUE TITLE
update bokeh plots

### ISSUE THREAD

**Issue by nhoffman** [nhoffman/ya16sdb#5]

**Comment by nhoffman** [comment]
use taxit to calculae lineages. Will need to adapt these commands:

```
export datadir=/mnt/disk2/molmicro/common/ncbi/16s/output/20180214
export named=$datadir/dedup/1200bp/named

singularity exec \
    -B $datadir \
     --pwd $datadir/dedup/1200bp/named /molmicro/common/singularity/taxtastic-0.8.5-singularity2.4.img \
    taxit lineage_table taxonomy.csv seq_info.csv -c lineages.csv

bin/prepare_plot_data.py \
    --details $named/filtered/details_out.csv \
    --seq-info $named/seq_info.csv \
    --lineages $named/lineages.csv \
    --hits $named/vsearch.tsv \
    -o $named/filtered_details.feather
```

**Comment by crosenth** [comment]
Including `lineage_table --taxonomy-table` per request

**Comment by crosenth** [comment]
[lineages.txt](https://github.com/nhoffman/ya16sdb/commit/1f9ad19c6654ed8a46f523a9ef0ddacb27495962#diff-cc8093822b396591a5530a463c87d048)

[lineages.csv](https://github.com/nhoffman/ya16sdb/commit/c3f18f963511cc8c593cab1fa2b82af160bd397a#diff-cc8093822b396591a5530a463c87d048)

[filtered_details.feather](https://github.com/nhoffman/ya16sdb/commit/89c085c9abe7792ec3cc322c7ea4a70a41c8f4d0#diff-cc8093822b396591a5530a463c87d048)
