### ISSUE TITLE
gateway timeouts

### ISSUE THREAD

**Issue by nhoffman** [nhoffman/ya16sdb#50]
Will fix in a branch from the 0.7.2 tag and release as 0.7.3

**Comment by nhoffman** [comment]
Note that dokku provides a command to set the timeout in 0.21.0 (which we aren't on yet)

https://dokku.com/docs/configuration/nginx/

**Comment by crosenth** [comment]
See Issue https://github.com/nhoffman/ya16sdb/issues/53
