### ISSUE TITLE
Checking my understanding of the 'type_classification' column in the new interface

### ISSUE THREAD

**Issue by marykstewart** [nhoffman/ya16sdb#51]
I'm going to include ya16sdb in a sequence classification job aid, and I want to make sure I understand the meaning of this column. I was thinking that it was still the best matching type strain, but the genus rank entry for FJ917551_1_1414 and MH283835_1_1424 confuses me. Can you please explain, or direct me to the docs? I looked through the README and checked the wiki, but didn't see an answer to this question.
  
<img width="909" alt="Screen Shot 2022-05-24 at 11 34 07 AM" src="https://user-images.githubusercontent.com/47676222/170108788-2f5e0569-524e-4566-853d-c67d6fc15bc9.png">

**Comment by crosenth** [comment]
It just means the nearest type strain was at the genus level threshold we use in NGS16S pipeline or 4 or more species level hits.  In this case most likely the former.  Yes I need to work on the docs, it's always been Issue https://github.com/nhoffman/ya16sdb/issues/1

**Comment by marykstewart** [comment]
Ok, thank you. I don't think enough of the folks who do seq review are aware that the website exists, or how it can be used to answer some of the questions that come up during sequence classification, so trying to change that. Wanted to confirm before I put my foot in my mouth.
